apiVersion: v1
kind: Pod
metadata:
  labels:
    app: omgwtfssl
  name: omgwtfssl
spec:
  restartPolicy: Never
  containers:
  - env:
    - name: SSL_SUBJECT
      value: nc.icraft.local
    - name: CA_SUBJECT
      value: admin@icraft.local
    - name: SSL_KEY
      value: /certs/nc.icraft.local.key
    - name: SSL_CSR
      value: /certs/nc.icraft.local.csr
    - name: SSL_CERT
      value: /certs/nc.icraft.local.crt
    name: omgwtfssl
    image: paulczar/omgwtfssl
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: certs
      name: certs
  volumes:
    - name: certs
      hostPath:
        path: "/opt/nextcloud-k8s/certs-pv"
